import './globals.css'
import { Inter } from 'next/font/google'

import Image from 'next/image';
import twitterIcon from '../resources/twitter.png';
import githubIcon from '../resources/github.png';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>




      <div className="TopBar inline-flex">
        <div className="p-2 px-10 fixed top-0 inset-x-0 justify-start flex gap-2 space-x-5">
          <div>          
            <a href="https://twitter.com/your_twitter" className="p-2">
              <Image src={twitterIcon} alt="Twitter" width={25} height={25} />
            </a>
          </div>
          <div>
            <a href="https://github.com/your_github" className="p-2">
              <Image src={githubIcon} alt="Github" width={25} height={25}  />
            </a>
          </div>
        </div>
      </div>

        {children}
     
      </body>
    </html>
  )
}